/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.unicundi.figurasgeometricas;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Polygon;

/**
 *
 * @author PROFESIONAL
 */
public class VistaGrafico extends javax.swing.JPanel {

    /**
     * Creates new form VistaGrafico
     */
    public VistaGrafico() {
        initComponents();
    }

    public void paint(Graphics g) {
        super.paint(g);
        //linea en x
        g.setColor(Color.red);
        g.drawLine(10, 250, 490, 250);
        // linea y
        g.setColor(Color.green);
        g.drawLine(250, 10, 250, 490);
        g.setColor(Color.BLACK);
        for (int i = 10; i < 500; i += 10) {

            g.drawLine(245, i, 255, i);
            g.drawLine(i, 245, i, 255);

        }

        int corde[][] = new int[4][4];
        corde[0][0] = 2;
        corde[0][1] = 2;
        corde[0][2] = -1;
        //corde[0][3] = -1;
        
        corde[1][0] = 1;
        corde[1][1] = -2;
        corde[1][2] = -2;
        //corde[1][3] = ;

        for (int i = 0; i < corde.length; i++) {
            if (corde[0][i] >= 0 ) {
                corde[0][i]=((corde[0][i] * 10) + 250);              
            }else{
                corde[0][i]=(250+(corde[0][i] * 10));              
            }
            
            if (corde[1][i] < 0 ) {                
                corde[1][i]=(250+(Math.abs(corde[1][i] * 10)));
            }else{               
                corde[1][i]=(250-Math.abs(corde[1][i] * 10));
            }
        }

        int coordx[] = {corde[0][0],corde[0][1],corde[0][2],corde[0][3]};
        int coordy[] = {corde[1][0],corde[1][1],corde[1][2],corde[1][3]};

        Polygon Polygon = new Polygon(coordx, coordy, 3);
        g.setColor(Color.BLUE);
        g.drawPolygon(Polygon);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
