/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.unicundi.figurasgeometricas;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Polygon;
import java.util.List;

/**
 * Clase para controlar todos los eventos y acciones del jframe
 *
 * @author Camilo Vargas
 */
public class VistaGrafico extends javax.swing.JPanel {

    /**
     * Creates new form VistaGrafico
     */
    /**
     * Lista para guardar los datos de las figuras
     */
    private List<List> datos;

    /**
     * Contructor principal de la clase
     */
    public VistaGrafico() {
        initComponents();
    }

    /**
     * Metodo para recibir las coordenadas de las figuras
     *
     * @param datos
     */
    public void RecibirCoordenadas(List<List> datos) {
        this.datos = datos;
    }

    /**
     * Metodo para pintar el plano y la figura
     *
     * @param g
     */
    public void paint(Graphics g) {
        super.paint(g);
        //linea en x
        g.setColor(Color.red);
        g.drawLine(10, 250, 490, 250);
        // linea y
        g.setColor(Color.green);
        g.drawLine(250, 10, 250, 490);
        g.setColor(Color.BLACK);
        for (int i = 10; i < 500; i += 10) {

            g.drawLine(245, i, 255, i);
            g.drawLine(i, 245, i, 255);

        }
        for (int i = 0; i < 2; i++) {
            System.out.println(datos.size());
            Polygon Polygon = new Polygon((int[]) this.datos.get(i).get(0), (int[]) this.datos.get(i).get(1), (int) this.datos.get(i).get(2));
            g.setColor((Color) this.datos.get(i).get(3));
            g.drawPolygon(Polygon);
            
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
