/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.unicundi.figurasgeometricas;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.LayoutManager;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 * Clase para controlar todos los eventos y acciones del jframe
 *
 * @author David Márquez
 */
public class VistaFiguras extends javax.swing.JFrame {

    /**
     * Creates new form VistaFiguras
     */
    /**
     * Variable para guardar los objetos
     */
    List lista = new ArrayList();
    /**
     * Variable para guardar el color dde la figura
     */
    Color colores = new Color(0, 0, 0);

    /**
     * Constructor principal de la clase
     */
    public VistaFiguras() {
        initComponents();

        this.getContentPane().setBackground(Color.WHITE);
        this.setLocationRelativeTo(null);
        cuadrado.setVisible(false);
        grafico.setVisible(false);
        mensaje.setVisible(false);
        //mensajePerimetro.setVisible(false);
        mensaje1.setVisible(false);
        mensaje2.setVisible(false);
        mensaje3.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        figuras = new javax.swing.JComboBox<String>();
        cuadrado = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        coor2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        coor3 = new javax.swing.JTextField();
        coor4 = new javax.swing.JTextField();
        lbCoor4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        coor1 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        mensaje = new javax.swing.JLabel();
        mensaje1 = new javax.swing.JLabel();
        mensaje2 = new javax.swing.JLabel();
        mensaje3 = new javax.swing.JLabel();
        grafico = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        color = new javax.swing.JComboBox<String>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Seleccione una figura:");

        figuras.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Cuadrado", "Rectangulo", "Triangulo" }));
        figuras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                figurasActionPerformed(evt);
            }
        });

        jLabel18.setText("Coordenada #1");

        jLabel19.setText("Coordenada #2");

        coor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coor2ActionPerformed(evt);
            }
        });

        jLabel20.setText("Coordenada #3");

        coor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coor3ActionPerformed(evt);
            }
        });

        coor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coor4ActionPerformed(evt);
            }
        });

        lbCoor4.setText("Coordenada #4");

        jLabel2.setText("Ingrese las coordenadas:");

        coor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coor1ActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Agregar");
        jToggleButton1.setActionCommand("Calcular");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        mensaje.setText("-");

        mensaje1.setText("-");

        mensaje2.setText("-");

        mensaje3.setText("-");

        javax.swing.GroupLayout graficoLayout = new javax.swing.GroupLayout(grafico);
        grafico.setLayout(graficoLayout);
        graficoLayout.setHorizontalGroup(
            graficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        graficoLayout.setVerticalGroup(
            graficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );

        jButton1.setText("Pintar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cuadradoLayout = new javax.swing.GroupLayout(cuadrado);
        cuadrado.setLayout(cuadradoLayout);
        cuadradoLayout.setHorizontalGroup(
            cuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuadradoLayout.createSequentialGroup()
                .addGroup(cuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cuadradoLayout.createSequentialGroup()
                        .addGroup(cuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cuadradoLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel2))
                            .addGroup(cuadradoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(cuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(cuadradoLayout.createSequentialGroup()
                                        .addGroup(cuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(cuadradoLayout.createSequentialGroup()
                                                .addComponent(jLabel19)
                                                .addGap(18, 18, 18)
                                                .addComponent(coor2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(cuadradoLayout.createSequentialGroup()
                                                .addComponent(jLabel18)
                                                .addGap(18, 18, 18)
                                                .addComponent(coor1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(cuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(cuadradoLayout.createSequentialGroup()
                                                .addComponent(jLabel20)
                                                .addGap(18, 18, 18)
                                                .addComponent(coor3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(cuadradoLayout.createSequentialGroup()
                                                .addComponent(lbCoor4)
                                                .addGap(18, 18, 18)
                                                .addComponent(coor4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(62, 62, 62)
                                        .addGroup(cuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(cuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jToggleButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addComponent(grafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(cuadradoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(cuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mensaje1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mensaje2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mensaje3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        cuadradoLayout.setVerticalGroup(
            cuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuadradoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGroup(cuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(coor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jToggleButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(coor4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCoor4)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mensaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensaje2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(mensaje3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(grafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel3.setText("Seleccione Color");

        color.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Rojo", "Azul", "Amarillo", "Verde", "Negro" }));
        color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(figuras, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(figuras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        figuras.getAccessibleContext().setAccessibleName("figuras");

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Metodo para establecer las acciones al seleccionar el dropdown
     *
     * @param evt
     */
    private void figurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_figurasActionPerformed

        switch (figuras.getSelectedIndex()) {
            case 0:
                cuadrado.setVisible(false);
                break;
            case 1:
                cuadrado.setVisible(true);
                coor1.setVisible(true);
                coor2.setVisible(true);
                coor3.setVisible(true);
                coor4.setVisible(true);
                lbCoor4.setVisible(true);

                break;
            case 2:
                cuadrado.setVisible(true);
                coor1.setVisible(true);
                coor2.setVisible(true);
                coor3.setVisible(true);
                coor4.setVisible(true);
                lbCoor4.setVisible(true);

                break;
            case 3:
                cuadrado.setVisible(true);
                coor4.setVisible(false);
                lbCoor4.setVisible(false);
                break;
        }


    }//GEN-LAST:event_figurasActionPerformed

    private void coor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coor2ActionPerformed

    private void coor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coor3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coor3ActionPerformed

    private void coor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coor4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coor4ActionPerformed

    private void coor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coor1ActionPerformed
    /**
     * Metodo para activar el evento del boton
     *
     * @param evt
     */
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed

        // valida el color de la figura
        switch (color.getSelectedIndex()) {
            case 0:
                colores = new Color(0, 0, 0);
                break;
            case 1:
                colores = new Color(255, 0, 0);
                break;
            case 2:
                colores = new Color(0, 0, 255);
                break;
            case 3:
                colores = new Color(255, 255, 0);
                break;
            case 4:
                colores = new Color(0, 255, 0);
                break;
            case 5:
                colores = new Color(0, 0, 0);
                break;
        }

        // valida el tipo de figura y calcula su area y su perimetro
        if (lista.size() >= 2) {
            JOptionPane.showMessageDialog(null, "No puede agregar mas de dos figuras");
        } else {
            switch (figuras.getSelectedIndex()) {
                case 0:
                    JOptionPane.showMessageDialog(null, "Seleccione una figura");
                    break;
                case 1:
                    Cuadrado cuadrado = new Cuadrado(coor1.getText(), coor2.getText(), coor3.getText(), coor4.getText());
                    cuadrado.setColores(this.colores);
                    if (cuadrado.separarCoordenadas() == true && cuadrado.getLado1() == cuadrado.getLado2()) {
                        lista.add(cuadrado);
                        JOptionPane.showMessageDialog(null, "Figura agregada");
                    } else {
                        JOptionPane.showMessageDialog(null, "No puede agregar esta figura, no es un cuadrado");
                    }

                    break;
                case 2:
                    Rectangulo rectangulo = new Rectangulo(coor1.getText(), coor2.getText(), coor3.getText(), coor4.getText());
                    rectangulo.setColores(this.colores);
                    if (rectangulo.separarCoordenadas() == true && rectangulo.getLado1() != rectangulo.getLado2()) {
                        lista.add(rectangulo);
                        JOptionPane.showMessageDialog(null, "Figura agregada");
                    } else {
                        JOptionPane.showMessageDialog(null, "No puede agregar esta figura, no es un rectangulo");
                    }

                    break;
                case 3:
                    Triangulo triangulo = new Triangulo(coor1.getText(), coor2.getText(), coor3.getText());
                    triangulo.setColores(this.colores);
                    if (triangulo.separarCoordenadas() == true) {
                        lista.add(triangulo);
                        JOptionPane.showMessageDialog(null, "Figura agregada");
                    } else {
                        JOptionPane.showMessageDialog(null, "No puede agregar esta figura, no es un triangulo");
                    }

                    break;
            }
        }


    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorActionPerformed
    /**
     * Metodo para establecer las acciones del boton
     *
     * @param evt
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VistaGrafico vistaGrafico = new VistaGrafico();
        vistaGrafico.setSize(500, 500);
        vistaGrafico.setLocation(0, 0);
        List<List> datos = new ArrayList<List>();
        if (lista.size() == 2) {
            for (int i = 0; i < lista.size(); i++) {

                if (lista.get(i) instanceof Cuadrado) {
                    ((Cuadrado) lista.get(i)).separarCoordenadas();
                    ((Cuadrado) lista.get(i)).hallarArea();
                    ((Cuadrado) lista.get(i)).hallarPerimetro();
                    ((Cuadrado) lista.get(i)).imprimirInfo();
                    mensaje1.setVisible(true);
                    mensaje1.setText("Cuadrado: " + ((Cuadrado) lista.get(i)).getMensaje());
                    ((Cuadrado) lista.get(i)).convertirCoordenadasPlano();
                    for (int j = 0; j < 2; j++) {
                        datos.add(new ArrayList());
                    }
                    datos.get(i).add(((Cuadrado) lista.get(i)).getCoordx());
                    datos.get(i).add(((Cuadrado) lista.get(i)).getCoordy());
                    datos.get(i).add(4);
                    datos.get(i).add(((Cuadrado) lista.get(i)).getColores());
                    vistaGrafico.RecibirCoordenadas(datos);
                    grafico.add(vistaGrafico, BorderLayout.CENTER);
                } else if (lista.get(i) instanceof Rectangulo) {
                    ((Rectangulo) lista.get(i)).separarCoordenadas();
                    ((Rectangulo) lista.get(i)).hallarArea();
                    ((Rectangulo) lista.get(i)).hallarPerimetro();
                    ((Rectangulo) lista.get(i)).imprimirInfo();
                    mensaje2.setVisible(true);
                    mensaje2.setText("Rectangulo: " + ((Rectangulo) lista.get(i)).getMensaje());
                    ((Rectangulo) lista.get(i)).convertirCoordenadasPlano();
                    for (int j = 0; j < 2; j++) {
                        datos.add(new ArrayList());
                    }
                    datos.get(i).add(((Rectangulo) lista.get(i)).getCoordx());
                    datos.get(i).add(((Rectangulo) lista.get(i)).getCoordy());
                    datos.get(i).add(4);
                    datos.get(i).add(((Rectangulo) lista.get(i)).getColores());
                    vistaGrafico.RecibirCoordenadas(datos);
                    grafico.add(vistaGrafico, BorderLayout.CENTER);
                } else {
                    ((Triangulo) lista.get(i)).separarCoordenadas();
                    ((Triangulo) lista.get(i)).hallarPerimetro();
                    ((Triangulo) lista.get(i)).hallarArea();
                    ((Triangulo) lista.get(i)).validarTipoTriangulo();
                    ((Triangulo) lista.get(i)).imprimirInfo();
                    mensaje3.setVisible(true);
                    mensaje3.setText("Trinagulo: " + ((Triangulo) lista.get(i)).getMensaje());
                    ((Triangulo) lista.get(i)).convertirCoordenadasPlano();
                    for (int j = 0; j < 2; j++) {
                        datos.add(new ArrayList());
                    }
                    datos.get(i).add(((Triangulo) lista.get(i)).getCoordx());
                    datos.get(i).add(((Triangulo) lista.get(i)).getCoordy());
                    datos.get(i).add(3);
                    datos.get(i).add(((Triangulo) lista.get(i)).getColores());
                    vistaGrafico.RecibirCoordenadas(datos);
                    grafico.add(vistaGrafico, BorderLayout.CENTER);
                }

            }
            grafico.setVisible(true);
            grafico.repaint();
        } else {
            JOptionPane.showMessageDialog(null, "Debe agregar dos figuras");
        }


    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * Metodo para activar el evento click del boton limpiar
     *
     * @param evt
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        lista.clear();
        grafico.removeAll();
        grafico.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * Contructor del awt
     *
     * @param args
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaFiguras().setVisible(true);
            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> color;
    private javax.swing.JTextField coor1;
    private javax.swing.JTextField coor2;
    private javax.swing.JTextField coor3;
    private javax.swing.JTextField coor4;
    private javax.swing.JPanel cuadrado;
    private javax.swing.JComboBox<String> figuras;
    private javax.swing.JPanel grafico;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lbCoor4;
    private javax.swing.JLabel mensaje;
    private javax.swing.JLabel mensaje1;
    private javax.swing.JLabel mensaje2;
    private javax.swing.JLabel mensaje3;
    // End of variables declaration//GEN-END:variables

    private LayoutManager BoxLayout(Container contentPane, int LINE_AXIS) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
