/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.unicundi.figurasgeometricas;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.LayoutManager;

/**
 *
 * @author PROFESIONAL
 */
public class VistaFiguras extends javax.swing.JFrame {

    /**
     * Creates new form VistaFiguras
     */
    public VistaFiguras() {
        initComponents();

        this.getContentPane().setBackground(Color.WHITE);
        this.setLocationRelativeTo(null);
        cuadrado.setVisible(false);
        grafico.setVisible(false);
        mensaje.setVisible(false);
        //mensajePerimetro.setVisible(false);
        mensaje.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        figuras = new javax.swing.JComboBox<>();
        cuadrado = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        coor2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        coor3 = new javax.swing.JTextField();
        coor4 = new javax.swing.JTextField();
        lbCoor4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        coor1 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        mensaje = new javax.swing.JLabel();
        grafico = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        color = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Seleccione una figura:");

        figuras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Cuadrado", "Rectangulo", "Triangulo" }));
        figuras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                figurasActionPerformed(evt);
            }
        });

        jLabel18.setText("Coordenada #1");

        jLabel19.setText("Coordenada #2");

        coor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coor2ActionPerformed(evt);
            }
        });

        jLabel20.setText("Coordenada #3");

        coor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coor3ActionPerformed(evt);
            }
        });

        coor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coor4ActionPerformed(evt);
            }
        });

        lbCoor4.setText("Coordenada #4");

        jLabel2.setText("Ingrese las coordenadas:");

        coor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coor1ActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Agregar");
        jToggleButton1.setActionCommand("Calcular");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        mensaje.setText("-");

        javax.swing.GroupLayout graficoLayout = new javax.swing.GroupLayout(grafico);
        grafico.setLayout(graficoLayout);
        graficoLayout.setHorizontalGroup(
            graficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        graficoLayout.setVerticalGroup(
            graficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );

        jButton1.setText("Pintar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cuadradoLayout = new javax.swing.GroupLayout(cuadrado);
        cuadrado.setLayout(cuadradoLayout);
        cuadradoLayout.setHorizontalGroup(
            cuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuadradoLayout.createSequentialGroup()
                .addGroup(cuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cuadradoLayout.createSequentialGroup()
                        .addGroup(cuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cuadradoLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel2))
                            .addGroup(cuadradoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(cuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(cuadradoLayout.createSequentialGroup()
                                        .addGroup(cuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(cuadradoLayout.createSequentialGroup()
                                                .addComponent(jLabel19)
                                                .addGap(18, 18, 18)
                                                .addComponent(coor2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(cuadradoLayout.createSequentialGroup()
                                                .addComponent(jLabel18)
                                                .addGap(18, 18, 18)
                                                .addComponent(coor1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(cuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(cuadradoLayout.createSequentialGroup()
                                                .addComponent(jLabel20)
                                                .addGap(18, 18, 18)
                                                .addComponent(coor3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(cuadradoLayout.createSequentialGroup()
                                                .addComponent(lbCoor4)
                                                .addGap(18, 18, 18)
                                                .addComponent(coor4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(62, 62, 62)
                                        .addGroup(cuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton1)
                                            .addComponent(jToggleButton1)))
                                    .addComponent(grafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(cuadradoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        cuadradoLayout.setVerticalGroup(
            cuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuadradoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGroup(cuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(coor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jToggleButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(coor4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCoor4)
                    .addComponent(jButton1))
                .addGap(51, 51, 51)
                .addComponent(mensaje)
                .addGap(18, 18, 18)
                .addComponent(grafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel3.setText("Seleccione Color");

        color.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Rojo", "Azul", "Amarillo", "Verde", "Negro" }));
        color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(figuras, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(figuras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        figuras.getAccessibleContext().setAccessibleName("figuras");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void figurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_figurasActionPerformed

        switch (figuras.getSelectedIndex()) {
            case 0:
                cuadrado.setVisible(false);
                break;
            case 1:
                cuadrado.setVisible(true);
                coor1.setVisible(true);
                coor2.setVisible(true);
                coor3.setVisible(true);
                coor4.setVisible(true);
                lbCoor4.setVisible(true);

                break;
            case 2:
                cuadrado.setVisible(true);
                coor1.setVisible(true);
                coor2.setVisible(true);
                coor3.setVisible(true);
                coor4.setVisible(true);
                lbCoor4.setVisible(true);

                break;
            case 3:
                cuadrado.setVisible(true);
                coor4.setVisible(false);
                lbCoor4.setVisible(false);
                break;
        }


    }//GEN-LAST:event_figurasActionPerformed

    private void coor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coor2ActionPerformed

    private void coor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coor3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coor3ActionPerformed

    private void coor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coor4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coor4ActionPerformed

    private void coor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coor1ActionPerformed
    /**
     * Metodo para activar el evento del boton
     *
     * @param evt
     */
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed

        // valida el color de la figura
        Color colores = new Color(0, 0, 0);
        switch (color.getSelectedIndex()) {
            case 0:
                colores = new Color(0, 0, 0);
                break;
            case 1:
                colores = new Color(255, 0, 0);
                break;
            case 2:
                colores = new Color(0, 0, 255);
                break;
            case 3:
                colores = new Color(255, 255, 0);
                break;
            case 4:
                colores = new Color(0, 255, 0);
                break;
            case 5:
                colores = new Color(0, 0, 0);
                break;
        }

        // valida el tipo de figura y calcula su area y su perimetro
        VistaGrafico vistaGrafico = new VistaGrafico();
        switch (figuras.getSelectedIndex()) {
            case 0:
                break;
            case 1:
                Cuadrado cuadrado = new Cuadrado(coor1.getText(), coor2.getText(), coor3.getText(), coor4.getText());
                cuadrado.separarCoordenadas();
                cuadrado.hallarArea();
                cuadrado.hallarPerimetro();
                cuadrado.imprimirInfo();
                mensaje.setVisible(true);
                mensaje.setText(cuadrado.getMensaje());
                cuadrado.convertirCoordenadasPlano();
                vistaGrafico.RecibirCoordenadas(cuadrado.getCoordx(), cuadrado.getCoordy(), 4, colores);

                break;
            case 2:
                Rectangulo rectangulo = new Rectangulo(coor1.getText(), coor2.getText(), coor3.getText(), coor4.getText());
                rectangulo.separarCoordenadas();
                rectangulo.hallarArea();
                rectangulo.hallarPerimetro();
                rectangulo.imprimirInfo();
                mensaje.setVisible(true);
                mensaje.setText(rectangulo.getMensaje());
                rectangulo.convertirCoordenadasPlano();
                vistaGrafico.RecibirCoordenadas(rectangulo.getCoordx(), rectangulo.getCoordy(), 4, colores);

                break;

            case 3:
                Triangulo triangulo = new Triangulo(coor1.getText(), coor2.getText(), coor3.getText());
                triangulo.separarCoordenadas();
                triangulo.validarTipoTriangulo();
                triangulo.hallarPerimetro();
                triangulo.hallarArea();
                triangulo.imprimirInfo();
                mensaje.setVisible(true);
                mensaje.setText(triangulo.getMensaje());
                triangulo.convertirCoordenadasPlano();
                vistaGrafico.RecibirCoordenadas(triangulo.getCoordx(), triangulo.getCoordy(), 3, colores);

                break;
        }
        vistaGrafico.setSize(500, 500);
        vistaGrafico.setLocation(0, 0);
        grafico.removeAll();
        grafico.add(vistaGrafico, BorderLayout.CENTER);
        grafico.revalidate();
        grafico.repaint();
        grafico.setVisible(true);


    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    /**
     *
     * @param args
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaFiguras().setVisible(true);
            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> color;
    private javax.swing.JTextField coor1;
    private javax.swing.JTextField coor2;
    private javax.swing.JTextField coor3;
    private javax.swing.JTextField coor4;
    private javax.swing.JPanel cuadrado;
    private javax.swing.JComboBox<String> figuras;
    private javax.swing.JPanel grafico;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lbCoor4;
    private javax.swing.JLabel mensaje;
    // End of variables declaration//GEN-END:variables

    private LayoutManager BoxLayout(Container contentPane, int LINE_AXIS) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
